switched to bounded rumq requests channel implementation
netology-group/svc-agent-rs pull request #50
Opened 2020-09-01 22:22 UTC by khodzha

2020-09-01 22:27 UTC, feymartynov requested changes

2020-09-01 22:27 UTC, feymartynov commented on src/mqtt.rs
> +            Err(e) => {
`if let Err(err) =`

2020-09-01 22:27 UTC, feymartynov commented on src/mqtt.rs
> +                .unwrap_or(DEFAULT_MQTT_REQUESTS_CHAN_SIZE),
Better to use `#[serde(default = 10_000)]`

2020-09-01 22:38 UTC, feymartynov approved these changes

2020-09-02 06:23 UTC, manifest approved these changes

2020-09-02 06:46 UTC, merged